title: 计算机基础课程
description: test test
theme: just-the-docs

url: https://lewisliu819.github.io

aux_links:
  "GitHub Repository":
    - "https://github.com/lewisliu819/coursewebsite"

nav:
  - title: "主页"
    url: /
  - title: "课程反馈"
    url: /feedback/
  - title: "关于我自己..."
    url: /about/