title: COMPSCI 0.10
description: ""
url: "https://lewisliu819.github.io/jdtest/" # the base hostname & protocol for your site, e.g. http://example.com
repository: lewisliu819/jdtest # for github-metadata

permalink: pretty

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"


theme: "just-the-docs"
nav_enabled: true

search_enabled: true
aux_links:
  "GitHub":
    - "https://github.com/jdtest"
show_topnav: true
